project:
  type: website
  output-dir: docs

website:
  title: "Inhalt"
  sidebar: 
    style: "docked"
    search: true
    contents:
    - section: "Einführung in R"
      contents:
      - Skript_1.1.qmd
      - Skript_1.2.qmd
      - Skript_1.3.qmd

    - section: "Datensätze"
      contents:
      - Skript_2.1.qmd
      - Skript_2.2.qmd
      - Skript_2.3.qmd

    - section: "Der Umgang mit Daten"
      contents:
      - Skript_3.1.qmd
      - Skript_3.2.qmd
      - Skript_3.3.qmd
      - Skript_3.4.qmd

    - section: "Die ersten Schritte bei der Datenanalyse"
      contents:
      - Skript_4.1.qmd
      - Skript_4.2.qmd
      - Skript_4.3.qmd
      - Skript_4.4.qmd

    - section: "Von einzelnen Antworten zum Index"
      contents:
      - Skript_5.1.qmd
      - Skript_5.2.qmd
      - Skript_5.3.qmd    

    - section: "Das Überprüfen von Unterschieden"
      contents:
      - Skript_6.1.qmd
      - Skript_6.2.qmd
      - Skript_6.3.qmd
      - Skript_6.4.qmd

    - section: "Das Überprüfen von Zusammenhängen"
      contents:
      - Skript_7.1.qmd
      - Skript_7.2.qmd
      - Skript_7.3.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

