project:
  type: website
  output-dir: docs

website:
  
  navbar: 
    title: false
    logo: Bilder/logo_ub_2021.png
    background: "#e3dac9"
    foreground: "secondary"
    search: true
    left: 
      - text: "Home"
        file: Home.qmd
      - text: "Der Kurs"
        file: Skript_1.1.qmd
      - text: "Die Grundidee"
        file: Hintergrund.qmd
      - text: "Die Autor:innen"
        file: Autoren.qmd
    
    right: 
      - icon: github
        href: https://github.com/patrickzerrer/R_Hands_on_Book
      - icon: twitter
        href: https://twitter.com/ZeMKI_Bremen
      
  sidebar: 
    style: "docked"
    background: "light"
    foreground: "secondary"
    contents:
    - section: "Data-Bootcamp: Einführung in R"
      contents:
      - Skript_1.1.qmd
      - Skript_1.2.qmd
      - Skript_1.3.qmd
      - Skript_1.4.qmd

    - section: "Data-Bootcamp: Datensätze"
      contents:
      - Skript_2.1.qmd
      - Skript_2.2.qmd
      - Skript_2.3.qmd

    - section: "Data-Bootcamp: Der Umgang mit Daten"
      contents:
      - Skript_3.1.qmd
      - Skript_3.2.qmd
      - Skript_3.3.qmd
      - Skript_3.4.qmd

    - section: "Die ersten Schritte bei der Datenanalyse"
      contents:
      - Skript_4.1.qmd
      - Skript_4.2.qmd
      - Skript_4.3.qmd
      - Skript_4.4.qmd

    - section: "Von einzelnen Antworten zum Index"
      contents:
      - Skript_5.1.qmd
      - Skript_5.2.qmd
      - Skript_5.3.qmd    

    - section: "Das Überprüfen von Unterschieden"
      contents:
      - Skript_6.1.qmd
      - Skript_6.2.qmd
      - Skript_6.3.qmd

    - section: "Das Überprüfen von Zusammenhängen"
      contents:
      - Skript_7.1.qmd
      - Skript_7.2.qmd
      - Skript_7.3.qmd
  
  page-footer: "Copyright 2023, Design by Katharina Maubach & Patrick Zerrer"

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

